######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 12 16:26:46 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
include(myqt.config)

# Input
HEADERS += ImageCanvas.h MainWindow.h MyCanvas.h
FORMS += MainWindow.ui
SOURCES += ImageCanvas.cpp main.cpp MainWindow.cpp MyCanvas.cpp
